### ISSUE TITLE
JSON error?

### ISSUE THREAD

**Issue by fuzheado** [tonythomas01/wikipedia-section-summaries#1]
Somehow I get this error:

Error: SyntaxError: Expected property name or '}' in JSON at position 1

**Comment by fuzheado** [comment]
Ah the console reads: "Failed to load resource: the server responded with a status of 429 (Bad Request)"

May want to report this error to the user directly? I may not have API credits or the server is busy with too many requests, which leads to this message.

**Comment by tonythomas01** [comment]
Aha, could be the server credits. But if you can paste the response in the network tab, I can take a look 
![Screenshot 2023-05-25 at 09 56 25](https://github.com/tonythomas01/wikipedia-section-summaries/assets/4214481/ca550249-15f0-450b-bdba-9369fc271b58)

**Comment by tonythomas01** [comment]
I can see that there is some better error handling in https://github.com/skripnik/wikipedia-section-summaries/commit/a3c4f15903eb5b2d9cc9bfcda30845c218144a78. Will port it here later.

**Comment by tonythomas01** [comment]
Ported in https://github.com/tonythomas01/wikipedia-section-summaries/commit/a8935cd28c62c4637dd218cdf713ff6aaf865e9b

**Comment by tonythomas01** [comment]
Closing as Resolved for now.
